[package]
name = "fungible-token"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
aegis-core = { workspace = true }
aegis-sdk = { workspace = true }

wee_alloc = "0.4.5"
serde_json = { workspace = true }
serde = { workspace = true }
borsh = { workspace = true }